export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_COCKTAIL_SUCCESS = 'FETCH_COCKTAIL_SUCCESS';
export const FETCH_COCKTAIL_FAIL = 'FETCH_COCKTAIL_FAIL';

export const ADD_COCKTAIL_SUCCESS = 'ADD_COCKTAIL_SUCCESS';
export const ADD_COCKTAIL_FAIL = 'ADD_COCKTAIL_FAIL';

export const DELETE_COCKTAIL_SUCCESS = 'DELETE_COCKTAIL_SUCCESS';

export const PUBLISH_COCKTAIL_SUCCESS = 'PUBLISH_COCKTAIL_SUCCESS';




